from langchain_google_genai import ChatGoogleGenerativeAI
from pydantic import SecretStr
from postgresdb.main_postgres import Postgres
from models import falseRes, trueRes
import json
import re

OUTPUT_FORMAT_INSTRUCTIONS = """
You MUST respond with ONLY a valid JSON object. No explanation, no markdown, no code fences.

Choose exactly one of these three shapes:

1. Text / clarifying question:
   {"type": "text", "response": "<your message here>"}

2. Table (query returned rows):
   {"type": "table", "response": {"columns": ["col1", "col2"], "rows": [[val, val], [val, val]]}}

3. Graph (two numeric series):
   {"type": "graph", "response": {"x": [...], "y": [...], "x_label": "...", "y_label": "..."}}

Rules:
- Use "text" when no data was fetched, when you need clarification, or the answer is purely descriptive.
- Use "table" when the SQL returned tabular rows.
- Use "graph" when the user explicitly asked for a chart/graph/plot OR when a trend over time is the clearest answer.
- Never mix shapes. Never add extra keys outside "type" and "response".
"""

SQL_GENERATION_SYSTEM = """You are an expert PostgreSQL query generator for the Qurate platform.

You will be given:
- The schema of the user's sandboxed database (tables, columns, types).
- The conversation history so far.
- The user's latest natural-language request.

Your job: produce ONE valid PostgreSQL query that satisfies the request.

Rules:
- Output ONLY the raw SQL statement. No explanation, no markdown, no code fences.
- NEVER reference any database or schema outside the one described in the schema context.
- NEVER use cross-database joins, dblink, postgres_fdw, or any mechanism that touches another DB.
- NEVER DROP or TRUNCATE tables unless the user's message explicitly says "delete everything" AND you prepend a -- DESTRUCTIVE comment.
- If the request is ambiguous or you need more information, output exactly: CLARIFY:<your question>
"""

SECURITY_SYSTEM = """You are a strict PostgreSQL security auditor for the Qurate platform.

You will be given:
- The user's sandboxed database name (the ONLY database they own).
- A SQL query generated by another LLM.

Your job: decide whether the query is safe to execute inside that sandbox.

Respond with ONLY one of:
  SAFE
  UNSAFE:<reason>

A query is UNSAFE if it:
- References any schema/database/table not belonging to the user's sandbox.
- Uses dblink, postgres_fdw, COPY TO/FROM with a filesystem path, pg_read_file, or similar.
- Attempts to CREATE/DROP ROLE, ALTER SYSTEM, or touch pg_catalog in a write context.
- Contains stacked statements designed to escape the sandbox (e.g. via DO $$ blocks calling external extensions).

If the query is genuinely fine, respond SAFE. Be strict but not paranoid about normal DML/DDL within the sandbox.
"""

FORMATTER_SYSTEM = """You are a response formatter for the Qurate platform.

You will be given:
- The original user question.
- The SQL query that was executed (may be None if no query ran).
- The raw result rows from PostgreSQL (may be empty).
- Column names of the result (may be empty).

Your job: decide the best output shape and return it.

""" + OUTPUT_FORMAT_INSTRUCTIONS


class SecurityAgent:
    """Checks that a generated SQL query stays within the user's sandbox DB."""

    def __init__(self, llm: ChatGoogleGenerativeAI):
        self._llm = llm

    def audit(self, sql: str, user_dbname: str) -> trueRes.SuccessRes | falseRes.ErrRes:
        prompt = (
            f"Sandboxed database name: {user_dbname}\n\n"
            f"SQL to audit:\n{sql}"
        )
        try:
            messages = [
                ("system", SECURITY_SYSTEM),
                ("human", prompt),
            ]
            result = self._llm.invoke(messages)
            verdict = result.text.strip()

            if verdict.startswith("SAFE"):
                return trueRes.SuccessRes(
                    status=200,
                    message="Security audit passed",
                    anotherValid={"safe": True}
                )
            else:
                reason = verdict.replace("UNSAFE:", "").strip()
                return falseRes.ErrRes(
                    status=403,
                    message=f"Security audit failed: {reason}",
                    anotherValid={"safe": False, "reason": reason}
                )
        except Exception as e:
            return falseRes.ErrRes(
                status=570,
                message="Security agent encountered an error",
                anotherValid=str(e)
            )


class Agent:
    def __init__(self, api_key: SecretStr):
        self._api = api_key
        self._llm = ChatGoogleGenerativeAI(
            model="gemini-3-flash-preview",
            api_key=self._api,
            temperature=0.2, 
        )
        self.security_agent = SecurityAgent(self._llm)

    def _get_schema_context(self, postgres_client: Postgres) -> str:
        """
        Queries information_schema to get all user tables + columns.
        Returns a readable string for the LLM prompt.
        """
        schema_query = """
            SELECT
                t.table_name,
                c.column_name,
                c.data_type,
                c.is_nullable
            FROM information_schema.tables t
            JOIN information_schema.columns c
                ON t.table_name = c.table_name
                AND t.table_schema = c.table_schema
            WHERE t.table_schema = 'public'
            ORDER BY t.table_name, c.ordinal_position;
        """
        result = postgres_client.executeQuery(schema_query)
        if result.status != 200 or not result.anotherValid:
            return "No tables found in this database."

        rows = result.anotherValid
        tables: dict[str, list[str]] = {}
        for table_name, col_name, data_type, nullable in rows:
            tables.setdefault(table_name, [])
            null_str = "NULL" if nullable == "YES" else "NOT NULL"
            tables[table_name].append(f"  {col_name} {data_type} {null_str}")

        lines = []
        for tbl, cols in tables.items():
            lines.append(f"Table: {tbl}")
            lines.extend(cols)
            lines.append("")
        return "\n".join(lines) if lines else "No tables found."

    @staticmethod
    def _build_history_string(chat_history: list[dict]) -> str:
        if not chat_history:
            return "No prior conversation."
        parts = []
        for turn in chat_history[-10:]:
            role = turn.get("role", "user")
            content = turn.get("content", "")
            parts.append(f"{role.upper()}: {content}")
        return "\n".join(parts)

    def _generate_sql(
        self,
        user_prompt: str,
        schema_context: str,
        history_string: str
    ) -> str:
        human_msg = (
            f"Database schema:\n{schema_context}\n\n"
            f"Conversation history:\n{history_string}\n\n"
            f"User request: {user_prompt}"
        )
        messages = [
            ("system", SQL_GENERATION_SYSTEM),
            ("human", human_msg),
        ]
        result = self._llm.invoke(messages)
        return result.text.strip()

    def _format_response(
        self,
        user_prompt: str,
        sql: str | None,
        rows: list,
        columns: list[str]
    ) -> dict:
        human_msg = (
            f"User question: {user_prompt}\n\n"
            f"SQL executed: {sql or 'None'}\n\n"
            f"Column names: {columns}\n\n"
            f"Result rows: {rows}"
        )
        messages = [
            ("system", FORMATTER_SYSTEM),
            ("human", human_msg),
        ]
        result = self._llm.invoke(messages)
        raw = result.text.strip()

        raw = re.sub(r"^```[a-z]*\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)

        try:
            parsed = json.loads(raw)
            if parsed.get("type") not in ("text", "table", "graph"):
                raise ValueError("Unknown type")
            return parsed
        except Exception:
            return {"type": "text", "response": raw}

    def execute_agent_query(
        self,
        user_prompt: str,
        postgres_client: Postgres,
        user_dbname: str,
        chat_history: list[dict] | None = None
    ) -> trueRes.SuccessRes | falseRes.ErrRes:
        """
        Full pipeline:
          1. Fetch schema
          2. Generate SQL (or CLARIFY)
          3. Security audit
          4. Execute SQL
          5. Format response into text / table / graph
        """
        try:
            chat_history = chat_history or []

            schema_context = self._get_schema_context(postgres_client)

            history_string = self._build_history_string(chat_history)
            generated = self._generate_sql(user_prompt, schema_context, history_string)

            if generated.startswith("CLARIFY:"):
                clarification = generated.replace("CLARIFY:", "").strip()
                return trueRes.SuccessRes(
                    status=200,
                    message="Agent requires clarification",
                    anotherValid={"type": "text", "response": clarification}
                )

            sql = generated

            audit_result = self.security_agent.audit(sql, user_dbname)
            if audit_result.status != 200:
                return falseRes.ErrRes(
                    status=403,
                    message=audit_result.message,
                    anotherValid={"type": "text", "response": f"Query blocked: {audit_result.message}"}
                )

            rows, columns = self._execute_and_get_columns(postgres_client, sql)
            if isinstance(rows, falseRes.ErrRes):
                return falseRes.ErrRes(
                    status=520,
                    message="SQL execution failed",
                    anotherValid={"type": "text", "response": f"SQL execution error: {rows.message}"}
                )

            formatted = self._format_response(user_prompt, sql, rows, columns)

            return trueRes.SuccessRes(
                status=200,
                message="Query executed successfully",
                anotherValid=formatted
            )

        except Exception as e:
            return falseRes.ErrRes(
                status=571,
                message=f"Agent pipeline error: {str(e)}",
                anotherValid={"type": "text", "response": "An internal error occurred. Please try again."}
            )

    def _execute_and_get_columns(
        self, postgres_client: Postgres, sql: str
    ) -> tuple[list, list[str]] | tuple[falseRes.ErrRes, list]:
        """Execute SQL and return (rows, column_names). Column names from cursor description."""
        try:
            postgres_client.cursor.execute(sql)  # type: ignore[arg-type]

            # DDL/DML statements (CREATE, INSERT, UPDATE, DELETE, ALTER, DROP)
            # don't produce result sets — cursor.description will be None
            desc = postgres_client.cursor.description
            if desc is None:
                # Return the command status (e.g. "CREATE TABLE", "INSERT 0 5")
                status_msg = postgres_client.cursor.statusmessage or "Command executed successfully"
                return [[status_msg]], ["result"]

            rows = postgres_client.cursor.fetchall() or []
            columns = [d[0] for d in desc]
            return rows, columns
        except Exception as e:
            err = falseRes.ErrRes(status=520, message=str(e), anotherValid=None)
            return err, []